name: Pylint
on: [push]
jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r RsPyTools/RsPyTools/requirements.txt && pylint --rcfile=RsPyTools/RsPyTools/.pylintrc --ignore=RsPyTools/RsPyTools/tests RsPyTools/RsPyTools/ > pylint.txt || true
      - uses: actions/upload-artifact@v1
        with:
          name: Pylint Result
          path: pylint.txt
      - run: cat pylint.txt
      - run: ./ci/compare.sh
