name: Remove old artifacts

on:
  schedule:
    # Every day at 1am UTC
    - cron: '0 1 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 week'
        skip-tags: true
        skip-recent: 2
